@attr(tags=['advanced'], required_hardware='false')
def test_20_deployvm_user_foruserincrossdomain(self):
    '\n        # Validate that Regular user should NOT be able to deploy vm for users in his domain\n\t'
    self.apiclient.connection.apiKey = self.user_d1a_apikey
    self.apiclient.connection.securityKey = self.user_d1a_secretkey
    vmData = {'name': 'd2a-d1a', 'displayname': 'd2a-d1a', }
    try:
        vm = VirtualMachine.create(self.apiclient, vmData, zoneid=self.zone.id, serviceofferingid=self.service_offering.id, templateid=self.template.id, networkids=self.network_d2a.id, accountid=self.account_d2a.name, domainid=self.account_d2a.domainid)
        self.fail('Regular user is allowed to deploy vm for users not in his domain ')
    except Exception as e:
        self.debug(('When user tries to deploy vm for users n different domain %s' % e))
        if (not CloudstackAclException.verifyMsginException(e, CloudstackAclException.NO_PERMISSION_TO_OPERATE_ACCOUNT)):
            self.fail('Error message validation failed when Regular user tries to deploy vm for users not in his domain ')
