def log_test_exceptions(func):

    def test_wrap_exception_log(self, *args, **kwargs):
        try:
            func(self, *args, **kwargs)
        except Exception as e:
            self.debug(('Test %s Failed due to Exception=%s' % (func, e)))
            raise e
    test_wrap_exception_log.__doc__ = func.__doc__
    return test_wrap_exception_log
