@attr('simulator_only', tags=['advanced'], required_hardware='false')
def test_29_restartNetwork_user_foruserinsamedomain(self):
    '\n        #Validate that Regular user should NOT be able to restart network for users in his domain\n\t'
    self.apiclient.connection.apiKey = self.user_d1a_apikey
    self.apiclient.connection.securityKey = self.user_d1a_secretkey
    try:
        restartResponse = self.network_d1b.restart(self.apiclient)
        self.fail('Regular user is allowed to restart network for users in his domain ')
    except Exception as e:
        self.debug(('When user tries to restart network for users in his domain %s' % e))
        if (not CloudstackAclException.verifyMsginException(e, CloudstackAclException.NO_PERMISSION_TO_OPERATE_ACCOUNT)):
            self.fail('Error message validation failed when Regular user tries to restart network for users in his domain ')
