def log_test_exceptions(func):

    def _log_test_exceptions(self, *args, **kwargs):
        try:
            func(self, *args, **kwargs)
        except Exception as e:
            self.debug(('Test %s Failed due to Exception=%s' % (func, e)))
            raise e
    return _log_test_exceptions
