def handleError(self, test, err):
    '\n        Adds Exception throwing test cases and information to log.\n        '
    self.printMsg(EXCEPTION, self.__testName, GetDetailExceptionInfo(err))
    self.__testResult = EXCEPTION
